import type { Workflow } from "./types"

export const sampleWorkflows: Workflow[] = [
  {
    id: "ai-petshop-assistant",
    title: "AI Petshop Assistant with GPT-4o, Google Calendar & WhatsApp/Instagram/FB",
    description:
      "This is honestly one of the cutest, smartest workflows I've ever built. It was designed with a lot of love to help petshops give their customers the best, modern, and smart service — without losing the personal touch. Imagine a client sending a message on WhatsApp, Instagram or Messenger, and it seconds, they're greeted with a kind message, a helpful menu, and everything they need. No delays. No queues. Just smooth, intelligent automation.",
    author: "Amanda Silva",
    difficulty: "Advanced",
    tags: ["AI", "GPT-4o", "Google Calendar", "WhatsApp", "Instagram", "Facebook", "Customer Service"],
    category: "AI & Machine Learning",
    views: 2847,
    downloads: 156,
    nodes: ["OpenAI", "Google Calendar", "WhatsApp", "Instagram", "Facebook"],
    createdAt: "2024-01-15",
    updatedAt: "2024-01-20",
  },
  {
    id: "automated-invoice-processing",
    title: "Automated Invoice Processing with OCR and Accounting Integration",
    description:
      "Streamline your invoice processing workflow by automatically extracting data from PDF invoices using OCR and integrating with your accounting software. This workflow handles invoice receipt, data extraction, validation, and automatic entry into QuickBooks or similar accounting systems.",
    author: "John Developer",
    difficulty: "Intermediate",
    tags: ["OCR", "Accounting", "PDF", "Automation", "QuickBooks"],
    category: "IT & DevOps",
    views: 1523,
    downloads: 89,
    nodes: ["PDF Parser", "OCR", "QuickBooks", "Email"],
    createdAt: "2024-01-10",
    updatedAt: "2024-01-18",
  },
  {
    id: "social-media-scheduler",
    title: "Multi-Platform Social Media Content Scheduler",
    description:
      "Schedule and publish content across multiple social media platforms with automatic hashtag suggestions and optimal posting times. This workflow analyzes your content, suggests the best times to post, and automatically publishes to Twitter, LinkedIn, and Facebook.",
    author: "Sarah Marketing",
    difficulty: "Beginner",
    tags: ["Social Media", "Scheduling", "Content", "Twitter", "LinkedIn", "Facebook"],
    category: "Marketing & Content",
    views: 3421,
    downloads: 234,
    nodes: ["Twitter", "LinkedIn", "Facebook", "Scheduler", "Content AI"],
    createdAt: "2024-01-05",
    updatedAt: "2024-01-22",
  },
  {
    id: "customer-support-ticket-routing",
    title: "Intelligent Customer Support Ticket Routing",
    description:
      "Automatically categorize and route customer support tickets to the right team members based on content analysis and priority scoring. Uses AI to analyze ticket content, determine urgency, and assign to the most appropriate support agent.",
    author: "Mike Support",
    difficulty: "Intermediate",
    tags: ["Customer Support", "Ticket Routing", "AI Classification", "Slack", "Zendesk"],
    category: "Customer Support & Helpdesk",
    views: 1876,
    downloads: 112,
    nodes: ["Zendesk", "Slack", "AI Classifier", "Email Parser"],
    createdAt: "2024-01-12",
    updatedAt: "2024-01-19",
  },
  {
    id: "lead-scoring-automation",
    title: "Advanced Lead Scoring and CRM Integration",
    description:
      "Automatically score leads based on multiple criteria and sync with your CRM system for better sales pipeline management. This workflow tracks user behavior, engagement metrics, and demographic data to calculate lead scores and trigger appropriate follow-up actions.",
    author: "Lisa Sales",
    difficulty: "Advanced",
    tags: ["Lead Scoring", "CRM", "Sales", "HubSpot", "Analytics"],
    category: "Sales & CRM",
    views: 2156,
    downloads: 145,
    nodes: ["HubSpot", "Lead Scorer", "Analytics", "Email Marketing"],
    createdAt: "2024-01-08",
    updatedAt: "2024-01-21",
  },
  {
    id: "home-security-monitoring",
    title: "Smart Home Security Monitoring System",
    description:
      "Monitor your home security cameras and sensors, sending alerts and notifications when unusual activity is detected. Integrates with popular smart home platforms and sends notifications via SMS, email, and push notifications.",
    author: "Tom HomeAuto",
    difficulty: "Beginner",
    tags: ["Home Automation", "Security", "Monitoring", "Notifications", "IoT"],
    category: "Personal & Home Automation",
    views: 987,
    downloads: 67,
    nodes: ["Camera API", "Motion Detector", "SMS", "Push Notifications"],
    createdAt: "2024-01-14",
    updatedAt: "2024-01-17",
  },
  {
    id: "ecommerce-order-fulfillment",
    title: "E-commerce Order Fulfillment Automation",
    description:
      "Complete order processing workflow that handles everything from order receipt to shipping notifications. Automatically processes payments, updates inventory, generates shipping labels, and sends tracking information to customers.",
    author: "Emma Commerce",
    difficulty: "Intermediate",
    tags: ["E-commerce", "Order Processing", "Inventory", "Shipping", "Shopify"],
    category: "Sales & CRM",
    views: 2341,
    downloads: 178,
    nodes: ["Shopify", "Stripe", "ShipStation", "Email", "Inventory Manager"],
    createdAt: "2024-01-03",
    updatedAt: "2024-01-16",
  },
  {
    id: "content-moderation-ai",
    title: "AI-Powered Content Moderation Pipeline",
    description:
      "Automatically moderate user-generated content using AI image and text analysis. Detects inappropriate content, spam, and policy violations across multiple platforms and takes appropriate action based on severity.",
    author: "Alex Security",
    difficulty: "Advanced",
    tags: ["AI", "Content Moderation", "Image Analysis", "Text Analysis", "Safety"],
    category: "AI & Machine Learning",
    views: 1654,
    downloads: 93,
    nodes: ["OpenAI Vision", "Text Classifier", "Image Analyzer", "Slack", "Database"],
    createdAt: "2024-01-07",
    updatedAt: "2024-01-23",
  },
  {
    id: "employee-onboarding-automation",
    title: "Employee Onboarding Automation Workflow",
    description:
      "Streamline new employee onboarding with automated account creation, document collection, and task assignment. Creates accounts across all necessary systems, sends welcome emails, and tracks onboarding progress.",
    author: "Rachel HR",
    difficulty: "Intermediate",
    tags: ["HR", "Onboarding", "Employee Management", "Google Workspace", "Slack"],
    category: "Productivity & Collaboration",
    views: 1432,
    downloads: 87,
    nodes: ["Google Workspace", "Slack", "BambooHR", "DocuSign", "Task Manager"],
    createdAt: "2024-01-11",
    updatedAt: "2024-01-24",
  },
  {
    id: "financial-report-generator",
    title: "Automated Financial Report Generator",
    description:
      "Generate comprehensive financial reports by pulling data from multiple sources including accounting software, banks, and payment processors. Automatically creates charts, calculates KPIs, and distributes reports to stakeholders.",
    author: "David Finance",
    difficulty: "Advanced",
    tags: ["Finance", "Reporting", "Analytics", "QuickBooks", "Charts"],
    category: "IT & DevOps",
    views: 1876,
    downloads: 124,
    nodes: ["QuickBooks", "Bank API", "Chart Generator", "PDF Creator", "Email"],
    createdAt: "2024-01-09",
    updatedAt: "2024-01-25",
  },
  {
    id: "blog-content-pipeline",
    title: "Automated Blog Content Creation Pipeline",
    description:
      "AI-powered blog content creation workflow that researches topics, generates outlines, creates content, optimizes for SEO, and publishes to your CMS. Includes fact-checking and plagiarism detection.",
    author: "Sophie Writer",
    difficulty: "Intermediate",
    tags: ["Content Creation", "AI Writing", "SEO", "WordPress", "Research"],
    category: "Marketing & Content",
    views: 2987,
    downloads: 201,
    nodes: ["OpenAI", "WordPress", "SEO Analyzer", "Plagiarism Checker", "Research API"],
    createdAt: "2024-01-06",
    updatedAt: "2024-01-26",
  },
  {
    id: "iot-device-monitoring",
    title: "IoT Device Health Monitoring System",
    description:
      "Monitor the health and performance of IoT devices across your network. Tracks device status, battery levels, connectivity, and performance metrics. Sends alerts when devices need attention or maintenance.",
    author: "Carlos IoT",
    difficulty: "Advanced",
    tags: ["IoT", "Monitoring", "Device Management", "MQTT", "Alerts"],
    category: "IT & DevOps",
    views: 1234,
    downloads: 76,
    nodes: ["MQTT", "InfluxDB", "Grafana", "SMS Alert", "Device API"],
    createdAt: "2024-01-13",
    updatedAt: "2024-01-27",
  },
  {
    id: "appointment-booking-system",
    title: "Smart Appointment Booking & Reminder System",
    description:
      "Complete appointment booking system with calendar integration, automated reminders, and rescheduling capabilities. Handles booking confirmations, sends reminders via multiple channels, and manages cancellations.",
    author: "Maria Scheduler",
    difficulty: "Beginner",
    tags: ["Appointments", "Calendar", "Reminders", "Booking", "SMS"],
    category: "Productivity & Collaboration",
    views: 3456,
    downloads: 267,
    nodes: ["Google Calendar", "SMS", "Email", "Calendly", "Reminder System"],
    createdAt: "2024-01-04",
    updatedAt: "2024-01-28",
  },
  {
    id: "data-backup-sync",
    title: "Multi-Cloud Data Backup & Sync Workflow",
    description:
      "Automatically backup and sync important data across multiple cloud storage providers. Ensures data redundancy, monitors backup integrity, and provides restoration capabilities with version control.",
    author: "Kevin Backup",
    difficulty: "Intermediate",
    tags: ["Backup", "Cloud Storage", "Data Sync", "AWS", "Google Drive"],
    category: "IT & DevOps",
    views: 1567,
    downloads: 98,
    nodes: ["AWS S3", "Google Drive", "Dropbox", "File Monitor", "Integrity Checker"],
    createdAt: "2024-01-02",
    updatedAt: "2024-01-29",
  },
  {
    id: "survey-analysis-automation",
    title: "Survey Response Analysis & Reporting",
    description:
      "Automatically analyze survey responses using AI sentiment analysis and generate comprehensive reports. Processes open-ended responses, categorizes feedback, and creates visualizations for stakeholder review.",
    author: "Nina Analytics",
    difficulty: "Intermediate",
    tags: ["Survey Analysis", "Sentiment Analysis", "Reporting", "AI", "Visualization"],
    category: "AI & Machine Learning",
    views: 1789,
    downloads: 134,
    nodes: ["Survey API", "Sentiment Analyzer", "Chart Generator", "Report Builder", "Email"],
    createdAt: "2024-01-01",
    updatedAt: "2024-01-30",
  },
  {
    id: "smart-home-energy-optimizer",
    title: "Smart Home Energy Usage Optimizer",
    description:
      "Optimize home energy consumption by monitoring usage patterns and automatically adjusting smart devices. Learns from your habits and preferences to minimize energy costs while maintaining comfort.",
    author: "Green Energy Pro",
    difficulty: "Advanced",
    tags: ["Smart Home", "Energy Optimization", "IoT", "Machine Learning", "Cost Savings"],
    category: "Personal & Home Automation",
    views: 2134,
    downloads: 156,
    nodes: ["Smart Thermostat", "Energy Monitor", "ML Optimizer", "Weather API", "Device Controller"],
    createdAt: "2023-12-28",
    updatedAt: "2024-01-31",
  },
]